<?php

require 'ProductContract.php';
require 'Product.php';
require 'Shop.php';

/* =================== DO NOT EDIT THIS FILE ============================ */

// Execute the test app
$Shop = new Shop;
$Shop->purchase(new Product('TV', 1250));
$Shop->purchase(new Product('Macbook', 2750.50));
$Shop->purchase(new Product('Headphones', 299));

echo PHP_EOL.'Purchased items: ' . PHP_EOL;
/** @var ProductContract  $Product */
foreach ($Shop->getProducts() as $Product) {
    echo $Product->getName() . ' : ' . $Product->getFormattedPrice() . PHP_EOL;
}
echo PHP_EOL;
